#!/bin/sh

source "${XDG_CONFIG_HOME:-$HOME/.config}"/colors.sh

options=(
	style=round
	width=4.5
	hidpi=on
	ax_focus=on
	active_color="$COLOR_GREEN"
	inactive_color="$COLOR_BG_1"
	background_color="$COLOR_BG_DIM"
)

borders "${options[@]}"
