#!/bin/sh

source "${XDG_CONFIG_HOME:-$HOME/.config}"/colors.sh

options=(
	style=round
	width=4.0
	hidpi=on
	active_color="$COLOR_ACCENT_BRIGHT"
	inactive_color="$COLOR_BG_1"
	background_color="$COLOR_BG_DIM"
)

borders "${options[@]}"
