#!/usr/bin/env sh

# Refrence:
# https://github.com/koekeishiya/yabai/wiki/Commands#message-passing-interface

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 all:32:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# exclude apps from tiling
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off

# hide menu bar
# yabai -m config menubar_opacity 0.0

# TODO:
# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"spaces-widget\"'"

# automatically flash the focused window when focus changes
yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"

echo "yabai configuration loaded..."
